package com.mg.eco.persistence.entity;
// Generated 29 Apr 2023, 23:27:47 by Hibernate Tools 6.1.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="trade"
)
public class Product  implements java.io.Serializable {


     private Integer productId;
     private User user;
     private String productName;
     private String productDesc;
     private long productPrice;
     private byte[] productImage;

    public Product() {
    }

    public Product(User user, String productName, String productDesc, long productPrice, byte[] productImage) {
       this.user = user;
       this.productName = productName;
       this.productDesc = productDesc;
       this.productPrice = productPrice;
       this.productImage = productImage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="seller_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="product_name", nullable=false, length=45)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="product_desc", nullable=false, length=45)
    public String getProductDesc() {
        return this.productDesc;
    }
    
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    
    @Column(name="product_price", nullable=false, precision=10, scale=0)
    public long getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(long productPrice) {
        this.productPrice = productPrice;
    }

    
    @Column(name="product_image", nullable=false)
    public byte[] getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(byte[] productImage) {
        this.productImage = productImage;
    }




}


